

export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const OBTENER_PROYECTOS_EXITO = "OBTENER_PROYECTOS_EXITO";
export const OBTENER_PROYECTOS_ERROR = "OBTENER_PROYECTOS_ERROR";

export const GUARDAR_PROYECTO = "GUARDAR_PROYECTO";
export const GUARDAR_EXITO = "GUARDAR_EXITO";
export const GUARDAR_ERROR = "GUARDAR_ERROR";

export const OBTENER_EDITAR = "OBTENER_EDITAR";
export const COMENZAR_EDITAR = "COMENZAR_EDITAR";
export const EDITAR_EXITO = "EDITAR_EXITO";
export const EDITAR_ERROR = "EDITAR_ERROR";

export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";
export const ELIMINAR_EXITO = "ELIMINAR_EXITO";
export const ELIMINAR_ERROR = "ELIMINAR_ERROR";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const OBTENER_TOKEN = "OBTENER_TOKEN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";




